version: '2'
services:
  watchtower:
    container_name: watchtower
    image: centurylink/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  db:
    container_name: db
    image: mysql
    restart: always
    volumes:
      - /home/users/sven/ontwikkelopdracht/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=fontys
      - MYSQL_PASSWORD=fontys
      - MYSQL_DATABASE=se2
      - MYSQL_RANDOM_ROOT_PASSWORD=true
  ontwikkelopdracht:
    container_name: ontwikkelopdracht
    image: svendub/se2-ontwikkelopdracht
    restart: always
    ports:
      - "80:80"
    links:
      - db


